[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "async-reminder"
version = "0.1.0"
description = "Асинхронный консольный таймер-напоминалка"
dependencies = ["aioconsole>=1.0.0"]
requires-python = ">=3.8"